name: 'md5_clean'

on:
  workflow_dispatch:
    inputs:
      day:
        description: 'which day ago to remove'
        required: false
        default: "180"
  schedule:
    - cron: '00 0 * * *'
    
env:
  day: ${{ github.event.inputs.day }}

permissions: write-all

jobs:
  CleanMD5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          wget https://raw.githubusercontent.com/Eloco/Script-collect/main/function/clean_md5_action.py
          python -m pip install --upgrade pip
          pip install fire
        
      - name: clean history file
        run: |
            if [ -z "${day}" ];then export day=180;fi
            echo ${day}
            d=`TZ=+8;date -d "${day} day ago" +"%Y%m%d%H%M%S"`;for file in `find ./ -not -path '*/.*' -type f `;do ( nd=`echo ${file} | sed 's/.*\(20[0-9]\{12\}\).*/\1/g'`;(if [ "$nd" -gt 0 ] 2>/dev/null; then ( if [ $d -gt $nd ];then (echo $file; rm $file);fi);fi));done

      - name: run clean_md5_action
        run: |
            python clean_md5_action.py
            rm clean_md5_action.py

      - name: Commit report and clean history
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout --orphan latest_branch
          git add -A
          git commit -am "clean md5 and history commit"
          git branch -D main
          git branch -m main
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push -f origin main
